#!/bin/sh
set -xeu

#export WEBKIT_HOME=$HOME/WebKit

export CC=clang
export CXX=clang++

. /etc/webkit/common-local.sh
unset WEBKIT_SDK_LOCAL_DEPS

export WEBKIT_BUILDDIR=$WEBKIT_HOME/WebKitBuild/clang-index-$PORT_LOWER
rm -fr $WEBKIT_BUILDDIR

cd $WEBKIT_HOME
b-webkit --$PORT_LOWER --configure-only --git-update

# Generate derived sources and such.
ninja -C $WEBKIT_BUILDDIR -t targets rule CUSTOM_COMMAND | grep -E "\.h\$" | xargs ninja -C $WEBKIT_BUILDDIR

# Re-configure for a debug build, so that the indexer knows about ASSERT and other Debug-only things.
b-webkit --$PORT_LOWER --debug --configure-only

# Merge compile commands in a single file
cmake --build $WEBKIT_BUILDDIR --target RewriteCompileCommands
cat $WEBKIT_BUILDDIR/compile_commands.json $WEBKIT_BUILDDIR/DeveloperTools/compile_commands.json | jq -s add > $WEBKIT_BUILDDIR/merged.json

# Generate index file.
/usr/local/clangd-indexer/bin/clangd-indexer --executor=all-TUs $WEBKIT_BUILDDIR/merged.json > $PORT_LOWER-clangd-index.idx
