#!/bin/bash

. /etc/webkit/common-local.sh

. $WEBKIT_HOME/local-build-options.sh

if [ -z "$WEBKIT_SDK_LOCAL_DEPS" ]
then
    echo "Please set WEBKIT_SDK_LOCAL_DEPS"
    exit 1
fi

b-webkit $ARGS $@
