#!/usr/bin/env python3
import os
import sys
import subprocess

WEBKIT_HOME = os.environ['WEBKIT_HOME']

from webkit_cli import OptionParser, runtime_environment

def main(argv):
    parser = OptionParser()
    options, args = parser.parse_known_args(argv)

    env = runtime_environment()

    target = os.path.basename(argv[0])

    base_outputdir = env.get('WEBKIT_OUTPUTDIR', os.path.join(WEBKIT_HOME, 'WebKitBuild'))
    if target != 'test-webkitpy':
        env['WEBKIT_OUTPUTDIR'] = os.path.join(base_outputdir, options.platform.upper(), options.configuration)

    argv[0] = os.path.join(WEBKIT_HOME, 'Tools', 'Scripts', target)
    if not os.path.isfile(argv[0]):
        argv[0] = os.path.join('/usr/local/bin', target)

    if target == 'run-webkit-tests':
        env['TZ'] = 'America/Los_Angeles'

    try:
        result = subprocess.call(argv, env=env)
    finally:
        gst_debug_file = env.get('GST_DEBUG_FILE')
        if gst_debug_file:
            subprocess.call(['rewrite-wk-gst-log', gst_debug_file])

    return result

if __name__ == '__main__':
    sys.exit(main(sys.argv))
