#!/usr/bin/env python3
import sys
import subprocess
from webkit_cli import runtime_environment

def main(args):
    env = runtime_environment()
    process_args = [env.get('SHELL', '/bin/bash'),]
    if args:
        process_args = args
    return subprocess.call(process_args, env=env)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
